rekruto/hello/urls.py
from django.urls import path

from . import views

app_name = 'hello'

urlpatterns = [
    path('', views.hello_user, name='hello_page')
]

rekruto/rekruto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hello.urls', namespace='hello')),
]

handler404 = 'hello.views.page_not_found'

rekruto/hello/views.py
from django.shortcuts import render


def hello_user(request):
    """
    hello_user(): обрабатывает GET передаёт в шаблон hello/main.html 
    имя и сообщенние для пользователя, в случае пустого GET 
    запроса в шаблон отправляются None.
    """
    if request.method == "GET":
        name = request.GET.get('name' or None)
        message = request.GET.get('message' or None)
        content = {
            'name': name,
            'message': message
        }
        return render(request, 'hello/main.html', content)


def server_error(request):
    """Кастомная страница ошибки Internal Server Error."""
    return render(request, 'errors_pages/500.html', status=500)


def page_not_found(request, exception):
    """Кастомная страница ошибки Not Found."""
    return render(request, 'errors_pages/404.html', status=404)

rekruto/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>  
    <title>
      {% block title %} Re-kruto!  {% endblock %}
    </title>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
  </head>
  <body>
    <header>
    {% include 'includes/header.html' %}
    </header>
    <main>
    {% block content %}
      <h1 class="text-center">
        <p>Контент не подвезли :( </p>
        <p>Попробуйте перейти по ссылке ниже:)</p>
        <p><a href="/?name=Rekruto&message=Давай%20дружить">Перейти!</a></p>
      </h1>
    {% endblock %}
    </main>
    <footer >
    {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

rekruto/templates/hello/main.html
{% extends 'base.html' %}
<head>
</head>
<body>
    {% block content %}    
    <div class="container">
        <h1 class="text-center">
            Hello
            {% if name %}
                {{ name }}!
            {% else %}
                Mr/Mrs. Incognito!
            {% endif %}
        </h1>
        <h2 class="text-center">
        {% if message %}
                {{ message }}!
            {% else %}
                no messages for you!
                <p>Try it:)</p>
                <p><a href="/?name=Rekruto&message=Давай%20дружить">Go!</a></p>
            {% endif %}
        </h2>
    </div>
    {% endblock %}
</body>
</html>

rekruto/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p> © 2022 Copyright <span style="color:black">Rekruto</p> 

rekruto/templates/includes/header.html
<nav class="navbar navbar-light" style="background-color: black">
  <div class="container">
    <a class="navbar-brand" href="{% url 'hello:hello_page' %}">
      <span style="color:white">Rekruto</a>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %}>  
    </a>       
  </div>
</nav> 